#!/usr/bin/with-contenv bash

if [ -n "${PASSWORD}" ] || [ -n "${HASHED_PASSWORD}" ]; then
    AUTH="password"
else
    AUTH="none"
    echo "starting with no password"
fi

if [ -z ${PROXY_DOMAIN+x} ]; then
    PROXY_DOMAIN_ARG=""
else
    PROXY_DOMAIN_ARG="--proxy-domain=${PROXY_DOMAIN}"
fi

# MRB commented out the `s6-setuidgid abc` line... s6-setuidgid runs the command as another user (abc) but we want to run it as root...
# MRB also changed all `/config` to `/root` because it's a lot easier to have everything in the normal home folder...
# MRB then later commented out the --user-data-dir and --extensions-dir flags... so that everything is under /root/.local/share/code-server
exec \
#    s6-setuidgid abc \
        /usr/local/bin/code-server \
            --bind-addr 0.0.0.0:8443 \
#            --user-data-dir /root/data \
#            --extensions-dir /root/extensions \
            --disable-telemetry \
            --auth "${AUTH}" \
            "${PROXY_DOMAIN_ARG}" \
            /root/workspace
